### ISSUE TITLE
outdated jsdom version

### ISSUE THREAD

**Issue by veke** [ikr/jsdom-test-browser#1]
I think this package is not installing on node v4 because of outdated jsdom 3 version depencendy. (contextify will fail on node 4)

"Note that as of our 4.0.0 release, jsdom requires io.js or Node.js 4 or newer (why?). In the meantime you are still welcome to install a release in the 3.x series if you use legacy Node.js versions like 0.10 or 0.12."

**Comment by veke** [comment]
https://github.com/brianmcd/contextify/issues/180

**Comment by ikr** [comment]
Yes, I gotta try it under Node 4, with the new jsdom, & release a new major version. I'll try to find some time for it on Friday

**Comment by veke** [comment]
Nice. Thanks.

**Comment by ikr** [comment]
Just published a v4.0.0 depending on the latest jsdom, and requiring Node 4+
